<?php

namespace App\Http\Controllers;

use App\Http\Requests\Url\StoreRequest;
use App\Models\Url;
use Auth;
use Illuminate\Http\Request;
use SEO;

class UrlsController extends Controller
{
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        SEO::setTitle(trans('meta.home.title'))->setDescription(trans('meta.home.description'));

        return view('common.home');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreRequest|Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request) {
        // Fresh again for overwrite key that generated by database
        $url = Url::create([
            'url' => $request->get('url'),
            'user_id' => Auth::id()
        ])->fresh();

        return view('common.home', [
            'url' => $url
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param Url $url
     * @return \Illuminate\Http\Response
     */
    public function show(Url $url) {
        return redirect()->to($url->url);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}
